
spring:
  freemarker:
#    template-loader-path: classpath/templates/
    suffix: .html
    check-template-location: true
    enabled: true
    content-type: text/html
    cache: false #缓存配置
    charset: UTF-8 #编码格式

  redis:
    database: 0
    port: 6379
    host: bdcRedis.gisyc.com
    timeout: PT3000s  #连接超时时间（毫秒）
    jedis.pool:
       # 连接池中的最大空闲连接
       max-idle:  3000
       # 连接池最大连接数（使用负值表示没有限制）
       max-active: 6000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#       max-wait: -1