
spring:
  freemarker:
#    template-loader-path: classpath/templates/
    suffix: .html
    check-template-location: true
    enabled: true
    content-type: text/html
    cache: false #缓存配置
    charset: UTF-8 #编码格式

#spring:
#  freemarker:
#    suffix: .html  #后缀名
#    content-type: text/html
#    enabled: true
#    cache: false #缓存配置
##    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
#    charset: UTF-8 #编码格式
#    settings:
#      number_format: '0.##'   #数字格式化，无小数点
